HW4
Arden30/TinkoffJavaBackendSpring23-24 pull request #4
Opened 2024-03-09 15:39 UTC by Arden30

2024-03-15 21:04 UTC, YuriiKondratov requested changes

2024-03-15 21:04 UTC, YuriiKondratov commented on migrations/master.xml
> +    <include file="link_to_chat.sql" relativeToChangelogFile="true"/>
давай объединим всё что относится к текущей миграции в один sql файл и разметим changeset`ы при помощи аннотаций как здесь в SQL-примере

2024-03-15 21:04 UTC, YuriiKondratov commented on scrapper/src/test/java/edu/java/scrapper/LiquibaseIntegrationTest.java
> +        PreparedStatement statement = connection.prepareStatement("INSERT INTO link (url, created_at) VALUES (?, ?)");
Я думаю лучше почистить таблички после этого теста, либо как-то по-другому проверить что миграции накатились (например, посмотреть список таблиц в БД)

2024-03-16 12:30 UTC, Arden30 commented on migrations/master.xml
> +    <include file="link_to_chat.sql" relativeToChangelogFile="true"/>
Исправил

2024-03-16 12:30 UTC, Arden30 commented on scrapper/src/test/java/edu/java/scrapper/LiquibaseIntegrationTest.java
> +        PreparedStatement statement = connection.prepareStatement("INSERT INTO link (url, created_at) VALUES (?, ?)");
Добавил чистку таблиц после теста

2024-03-22 17:38 UTC, YuriiKondratov approved these changes

2024-03-23 12:09 UTC, merged