HW5
Arden30/TinkoffJavaBackendSpring23-24 pull request #5
Opened 2024-03-17 20:02 UTC by Arden30

В этом дз пытался помимо основных задач наконец-таки связать сервисы bot и scrapper, из-за чего нужно поменять тесты команд в модуле бота (пока не успел, постараюсь добавить в ближайшие дни).
Правда при попытке запустить приложение возникла проблема при обращении через ScrapperWebClient к сервису scrapper, какие-то проблемы возникают с ssl (Exception in thread "OkHttp Dispatcher" org.springframework.web.reactive.function.client.WebClientRequestException: not an SSL/TLS record), не понимаю как исправить...
Ещё есть вопрос, можно ли в течение следующей недели после дедлайна дослать бонусное дз 5? Очень много дедлайнов навалилось на эту неделю по всем фронтам...

2024-03-24 09:26 UTC, YuriiKondratov commented
Привет! Бонусное посмотрю, но один раз (то есть поднять балл путем исправлений будет нельзя).

2024-03-24 09:47 UTC, YuriiKondratov requested changes

2024-03-24 09:47 UTC, YuriiKondratov commented on migrations/schema.sql
> +    id              bigint,
Давай по-взрослому сделаем. Если какие-то фиксы в схему бд вносишь, то делаешь новую миграцию, а не исправляешь старую.

2024-03-24 09:47 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcChatRepository.java
> +        return jdbcTemplate.query(FIND_ALL, new BeanPropertyRowMapper<>(Chat.class));
У тебя получается, что при каждом запросе будет создаваться один и тот же новый RowMapper. Давай сделаем так, чтобы он создавался только один раз и переиспользовался в запросах.

2024-03-24 09:47 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcLinkRepository.java
> +        return jdbcTemplate.query(FIND_ALL, new BeanPropertyRowMapper<>(Link.class), chatId);
Аналогичное замечание про RowMapper

2024-03-24 09:47 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcLinkRepository.java
> +            throw new DoubleLinkException("Link is already being tracked");
А зчем эксепшн? Если ссылка уже добавлена, то всё ок же, можно просто ничего не делать. Либо если бросаешь эксепшн, то обработай его в сервисе, чтобы в итоге всё было [идемпотентно](https://developer.mozilla.org/ru/docs/Glossary/Idempotent)

2024-03-24 09:47 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcLinkRepository.java
> +            throw new NoSuchLinkException("No such link");
А зачем эксепшн? Если ссылки и так нет, то и удалять нечего, значит всё ок

2024-03-24 09:47 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/schedulers/updater/LinkUpdaterImpl.java
> +public class LinkUpdaterImpl implements LinkUpdater {
Давай теперь по поводу этого класса.

У тебя жестко захардкожены два источника - github и stackoverflow. Че будем делать когда ещё один источник появится? А когда их станет 100? Давай объединим логику обработки обновлений интерфейсом. Например: interface LinkUpdateProcessorService { public String process(Link link); } и сделаем конкретные реализации. Например: GithubLinkUpdateProcessorService и StackOverflowLinkUpdateProcessorService. Каждый класс будет ходить в свой клиент и проверять наличие обновлений.

2024-03-24 09:47 UTC, YuriiKondratov commented on scrapper/src/test/java/edu/java/scrapper/integration_tests/JdbcRepositoryTest.java
> +    @BeforeEach
Тут наверное лучше сделать AfterEach, чтобы после последнего теста тоже база почистилась

2024-03-24 15:04 UTC, Arden30 commented on migrations/schema.sql
> +    id              bigint,
Ок, учту в следующие разы. В бонусной домашке я как раз делал новую миграцию для новой таблицы

2024-03-24 15:04 UTC, Arden30 commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcChatRepository.java
> +        return jdbcTemplate.query(FIND_ALL, new BeanPropertyRowMapper<>(Chat.class));
Исправил

2024-03-24 15:04 UTC, Arden30 commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcLinkRepository.java
> +        return jdbcTemplate.query(FIND_ALL, new BeanPropertyRowMapper<>(Link.class), chatId);
Исправил

2024-03-24 15:13 UTC, Arden30 commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcLinkRepository.java
> +            throw new DoubleLinkException("Link is already being tracked");
Перенес обработку исключения в сервис. Это исключение нужно, чтобы в случае повторного добавления ссылки scrapper отправил ошибку боту, а тот вывел пользователю сообщение о том, что ссылка отслеживается

2024-03-24 15:13 UTC, Arden30 commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcLinkRepository.java
> +            throw new NoSuchLinkException("No such link");
Аналогично предыдущему

2024-03-24 15:14 UTC, Arden30 commented on scrapper/src/test/java/edu/java/scrapper/integration_tests/JdbcRepositoryTest.java
> +    @BeforeEach
Исправил

2024-03-24 15:50 UTC, Arden30 commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcLinkRepository.java
> +            throw new DoubleLinkException("Link is already being tracked");
Исправил

2024-03-24 15:50 UTC, Arden30 commented on scrapper/src/main/java/edu/java/schedulers/updater/LinkUpdaterImpl.java
> +public class LinkUpdaterImpl implements LinkUpdater {
Исправил

2024-03-27 12:11 UTC, YuriiKondratov approved these changes

2024-03-29 19:49 UTC, merged